### PR TITLE
Feature bitcode release

### PR DESCRIPTION
**Pull request by Kelmatou**
This PL brings support for release version failing to compile due to framework not built with full bitcode.

### CODE REVIEW

**Comment by AFathi** [comment]
@Kelmatou, thank you for contributing to **ARVideoKit**!

**Comment by omarojo** [comment]
Why is the ARVideoKitRelease scheme not visible/not in the project.

**Comment by AFathi** [comment]
@omarojo, thanks for noting that out will fix this issue and submit it. I'd suggest to use whatever fits your project needs!

In the latest release I have added Cocoapods and Carthage (package managers) support and I'll be adding Swift Package Manager support in future updates.

**Comment by AFathi** [comment]
@omarojo, do you mind sharing how are you currently implementing **ARVideoKit** into your project?

**Comment by omarojo** [comment]
I ended up cloning Kelmatou’s branch that had the Release scheme to build the framework.

I dont wanna use cocoapods or any of that because I plan to use ARVideokit as a component of a larger framework.

I expect my Developer Users to drag&drop MyFramework that uses ARVideoKit framework and start developing with it. So they will have to drag&drop both separately.

**Comment by AFathi** [comment]
@omarojo, I'd recommend copying the [**ARVideoKit**](https://github.com/AFathi/ARVideoKit/tree/master/ARVideoKit) folder into your project rather than using the framework as a whole because it would improve the [app startup time](https://developer.apple.com/videos/play/wwdc2017/413/).

**Pull request merged**
