### PR TITLE
Fix memory leaks

### PR DESCRIPTION
**Pull request by asam139**
FIX MEMORY LEAKS:
- Parent view reference must be weak
- Use weak proxy to broke memory leak with CADisplayLink
- Use private properties in place of global

### CODE REVIEW

**Comment by AFathi** [comment]
Great job @asam139. Love your contributions.

**Comment by mourlamstudios** [comment]
100k+ leaks when running ARVideoKit-Example using SceneKit and recording for a few seconds using these updates.

Screen Shot 2019-05-12 at 1 55 42 PM

**Comment by asam139** [comment]
> 100k+ leaks when running ARVideoKit-Example using SceneKit and recording for a few seconds using these updates.
> 
> Screen Shot 2019-05-12 at 1 55 42 PM

Hi @mourlamstudios, I have checked if theses leak memories existed before this pull request and it exists. So this pull request is not the problem, these leak memory leaks are of the beginning.

**Comment by AFathi** [comment]
@mourlamstudios, thanks for sharing this. Will investigate the source of the leaks and push some changes when I get the chance to.

**Comment by pixelworship** [comment]
@asam139 Ah ok. I got excited when I saw the title of the PR "Fix memory leaks". I figured it fixed all the memory leaks I've been seeing. I noticed the retain cycles in previous releases as well. Glad to see you resolved those. I'll try to take a look at the memory leaks this week as well.

**Pull request merged**
